version: '3.8'
services:
  postgres:
    image: postgres:15
    container_name: monolith-db
    restart: always
    environment:
      POSTGRES_DB: scalable-analyzer
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  monolith:
    build: .
    container_name: monolith-app
    restart: always
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/scalable-analyzer
      SPRING_DATASOURCE_USERNAME: myuser
      SPRING_DATASOURCE_PASSWORD: mypassword
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_APPLICATION_NAME: monolith
    ports:
      - "8080:8080"

volumes:
  postgres_data: