

services:
  postgres:
    image: postgres:15
    container_name: shared_postgres
    restart: always
    environment:
      POSTGRES_DB: scalable-analyzer
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    ports:
      - "5433:5432"  # Change external port to 5433 to avoid conflicts

  cart:
    build:
      context: ./cart
      dockerfile: Dockerfile
    container_name: cart_service
    restart: always
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/scalable-analyzer
      SPRING_DATASOURCE_USERNAME: myuser
      SPRING_DATASOURCE_PASSWORD: mypassword
    ports:
      - "8085:8085"

  order:
    build:
      context: ./order
      dockerfile: Dockerfile
    container_name: order_service
    restart: always
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/scalable-analyzer
      SPRING_DATASOURCE_USERNAME: myuser
      SPRING_DATASOURCE_PASSWORD: mypassword
    ports:
      - "8084:8084"

  product:
    build:
      context: ./product
      dockerfile: Dockerfile
    container_name: product_service
    restart: always
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/scalable-analyzer
      SPRING_DATASOURCE_USERNAME: myuser
      SPRING_DATASOURCE_PASSWORD: mypassword
    ports:
      - "8082:8082"

  user:
    build:
      context: ./user
      dockerfile: Dockerfile
    container_name: user_service
    restart: always
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/scalable-analyzer
      SPRING_DATASOURCE_USERNAME: myuser
      SPRING_DATASOURCE_PASSWORD: mypassword
    ports:
      - "8083:8083"

  microbridge:
    build:
      context: ./microbridge
      dockerfile: Dockerfile
    container_name: microbridge_service
    restart: always
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/scalable-analyzer
      SPRING_DATASOURCE_USERNAME: myuser
      SPRING_DATASOURCE_PASSWORD: mypassword
    ports:
      - "8081:8081"